export const SET_USER_INFO = 'SET_USER_INFO';
export const UPDATE_MODAL_PROPS = 'UPDATE_MODAL_PROPS';
export const RESET_REDUX_STORE = 'RESET_REDUX_STORE';
export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';

export const TRANSACTION_CONTACTS_SUCCESS = 'TRANSACTION_CONTACTS_SUCCESS';
export const GET_ALL_TRANSACTIONS_SUCCESS = 'GET_ALL_TRANSACTIONS_SUCCESS';
export const SEARCH_CONTACTS_SUCCESS = 'SEARCH_CONTACTS_SUCCESS';
